// Generated by ChatGPT

use std::io;
use std::net::{IpAddr, Ipv4Addr, SocketAddr, UdpSocket};

fn main() -> io::Result<()> {
	let socket = UdpSocket::bind("0.0.0.0:12345")?;

	// Set the address of the server
	let server_addr = SocketAddr::new(IpAddr::V4(Ipv4Addr::new(127, 0, 0, 1)), 12345);

	let message = "Hello, server!".as_bytes();
	socket.send_to(message, server_addr)?;

	let mut buffer = [0; 1024];
	let (n, src) = socket.recv_from(&mut buffer)?;

	println!("Received from server: {}", String::from_utf8_lossy(&buffer[..n]));

	Ok(())
}
